version: 0.0
os: linux
files:
  - source: /
    destination: /opt/kakeai
permissions:
  - object: /opt/kakeai
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/setup.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      runas: ec2-user
